export const excercises: any = {
  biceps: [
    {
      ex: 'biceps1',
      title: 'machine curls',
      img: 'assets/images/biceps (1).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps2',
      title: 'barbell preacher curl',
      img: 'assets/images/biceps (2).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps3',
      title: 'incline dumbbell biceps curl',
      img: 'assets/images/biceps (3).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'biceps4',
    //   title: 'standing dumbbell curl',
    //   img: 'assets/images/biceps (4).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'biceps5',
      title: 'one arm dumbbell preacher curl',
      img: 'assets/images/biceps (5).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps6',
      title: 'concentration curls',
      img: 'assets/images/biceps (6).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps7',
      title: 'cable biceps curl',
      img: 'assets/images/biceps (7).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps8',
      title: 'standing hammer curl',
      img: 'assets/images/biceps (8).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'biceps9',
    //   title: 'reverse grip barbell curl',
    //   img: 'assets/images/biceps (9).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'biceps10',
    //   title: 'one arm low pulley curls',
    //   img: 'assets/images/biceps (10).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'biceps11',
    //   title: 'standing high pulley curl',
    //   img: 'assets/images/biceps (11).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'biceps12',
      title: 'standing barbell curls',
      img: 'assets/images/biceps (12).jpg',
      desc: 'desc',
    },
    {
      ex: 'biceps13',
      title: 'alternating dumbbell hammer curl',
      img: 'assets/images/biceps (13).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'biceps14',
    //   title: 'dumbbell hammer preacher curl',
    //   img: 'assets/images/biceps (14).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'biceps15',
    //   title: 'cable peacher curl',
    //   img: 'assets/images/biceps (15).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'biceps16',
    //   title: 'cable revers curl',
    //   img: 'assets/images/biceps (16).jpg',
    //   desc: 'desc',
    // },
  ],
  shoulder: [
    {
      ex: 'shoulder1',
      title: 'one arm standing dumbbel press',
      img: 'assets/images/shoulder (1).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'shoulder2',
    //   title: 'barbell front raises',
    //   img: 'assets/images/shoulder (2).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'shoulder3',
      title: 'dumbbell lateral raises',
      img: 'assets/images/shoulder (3).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'shoulder4',
    //   title: 'upright rows',
    //   img: 'assets/images/shoulder (4).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder5',
    //   title: 'bent over lateral  raises',
    //   img: 'assets/images/shoulder (5).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'shoulder6',
      title: 'nautilus lateral raises',
      img: 'assets/images/shoulder (6).jpg',
      desc: 'desc',
    },
    {
      ex: 'shoulder7',
      title: 'standing dumbbell front raise',
      img: 'assets/images/shoulder (7).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'shoulder8',
    //   title: 'side-lying lateral raises',
    //   img: 'assets/images/shoulder (8).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'shoulder9',
      title: 'single arm cable lateral raises',
      img: 'assets/images/shoulder (9).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'shoulder10',
    //   title: 'single arm cable front raises',
    //   img: 'assets/images/shoulder (10).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder11',
    //   title: 'low pulley bent-over lateral raises',
    //   img: 'assets/images/shoulder (11).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder12',
    //   title: 'onde-dumbbell front raises',
    //   img: 'assets/images/shoulder (12).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder13',
    //   title: 'back seated military press',
    //   img: 'assets/images/shoulder (13).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder14',
    //   title: 'front seated military press',
    //   img: 'assets/images/shoulder (14).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder15',
    //   title: 'arnold dumbbell press',
    //   img: 'assets/images/shoulder (15).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder16',
    //   title: 'cable upright row',
    //   img: 'assets/images/shoulder (16).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'shoulder17',
    //   title: 'dumbbell upraight row',
    //   img: 'assets/images/shoulder (17).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'shoulder18',
      title: 'seaated machine shoulder press',
      img: 'assets/images/shoulder (18).jpg',
      desc: 'desc',
    },
    {
      ex: 'shoulder19',
      title: 'Cable Rope Rear-Delt Rows',
      img: 'assets/images/shoulder (19).jpg',
      desc: 'desc',
    },
  ],
  back: [
    // {
    //   ex: 'back1',
    //   title: 'chin ups',
    //   img: 'assets/images/back (1).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back2',
    //   title: 'pull ups',
    //   img: 'assets/images/back (2).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'back3',
      title: 'lat pulldowns',
      img: 'assets/images/back (3).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'back4',
    //   title: 'back lat pulldowns',
    //   img: 'assets/images/back (4).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back5',
    //   title: 'v-bar lat pulldowns',
    //   img: 'assets/images/back (5).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back6',
    //   title: 'straight-arm lat pulldowns',
    //   img: 'assets/images/back (6).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'back7',
      title: 'seated cable rows',
      img: 'assets/images/back (7).jpg',
      desc: 'desc',
    },
    {
      ex: 'back8',
      title: 'one-arm dumbbell rows',
      img: 'assets/images/back (8).jpg',
      desc: 'desc',
    },
    {
      ex: 'back9',
      title: 'bent over row',
      img: 'assets/images/back (9).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'back10',
    //   title: 'machine t-bat rows',
    //   img: 'assets/images/back (10).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back11',
    //   title: 'inverted row',
    //   img: 'assets/images/back (11).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back12',
    //   title: 'cable incline pushdown',
    //   img: 'assets/images/back (12).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back13',
    //   title: 'superman',
    //   img: 'assets/images/back (13).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'back14',
    //   title: 'machine reverse fly',
    //   img: 'assets/images/back (14).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'back15',
      title: 'Hammer Strength Row',
      img: 'assets/images/back (15).jpg',
      desc: 'desc',
    },
    {
      ex: 'back16',
      title: 'Machine Low Row',
      img: 'assets/images/back (16).jpg',
      desc: 'desc',
    },
  ],
  buttocks: [
    {
      ex: 'buttocks1',
      title: 'one leg cable kickback',
      img: 'assets/images/buttocks (1).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks2',
      title: 'machine hip extensions',
      img: 'assets/images/buttocks (2).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks3',
      title: 'floor hip extension',
      img: 'assets/images/buttocks (3).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks4',
      title: 'bridging',
      img: 'assets/images/buttocks (4).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks5',
      title: 'cable hip abductions',
      img: 'assets/images/buttocks (5).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks6',
      title: 'standing machine hip abductions',
      img: 'assets/images/buttocks (6).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks7',
      title: 'floor hip abductions',
      img: 'assets/images/buttocks (7).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks8',
      title: 'seated machine hip abductions',
      img: 'assets/images/buttocks (8).jpg',
      desc: 'desc',
    },
    {
      ex: 'buttocks9',
      title: 'back extension',
      img: 'assets/images/buttocks (9).jpg',
      desc: 'desc',
    },
  ],
  calf: [
    // {
    //   ex: 'calf1',
    //   title: 'seated barbell calf raises',
    //   img: 'assets/images/calf (1).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf2',
    //   title: 'sranding barbell calf raises',
    //   img: 'assets/images/calf (2).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf3',
    //   title: 'seated calf raises',
    //   img: 'assets/images/calf (3).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf4',
    //   title: 'one-leg toe raises',
    //   img: 'assets/images/calf (4).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'calf5',
      title: 'machine calf press',
      img: 'assets/images/calf (5).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'calf6',
    //   title: 'sumbbell calf raise seated single leg',
    //   img: 'assets/images/calf (6).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf7',
    //   title: 'one leg bodyweight calf raise',
    //   img: 'assets/images/calf (7).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf8',
    //   title: 'cable calf raise single leg',
    //   img: 'assets/images/calf (8).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'calf9',
    //   title: 'cable calf raise',
    //   img: 'assets/images/calf (9).jpg',
    //   desc: 'desc',
    // },
  ],
  legs: [
    {
      ex: 'legs1',
      title: 'leg extension',
      img: 'assets/images/legs (1).jpg',
      desc: 'desc',
    },
    {
      ex: 'legs2',
      title: 'machine adductions',
      img: 'assets/images/legs (2).jpg',
      desc: 'desc',
    },
    {
      ex: 'legs3',
      title: 'lying leg curls',
      img: 'assets/images/legs (3).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'legs4',
    //   title: 'standing leg curls',
    //   img: 'assets/images/legs (4).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'legs5',
      title: 'dumbbell lunge',
      img: 'assets/images/legs (5).jpg',
      desc: 'desc',
    },
    {
      ex: 'legs6',
      title: 'seated leg curls',
      img: 'assets/images/legs (6).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'legs7',
    //   title: 'good mornings',
    //   img: 'assets/images/legs (7).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs8',
    //   title: 'cable adductions',
    //   img: 'assets/images/legs (8).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs9',
    //   title: 'dumbbell squats',
    //   img: 'assets/images/legs (9).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs10',
    //   title: 'stiff-legged deadlifts',
    //   img: 'assets/images/legs (10).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs11',
    //   title: 'squats',
    //   img: 'assets/images/legs (11).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs12',
    //   title: 'deadlifts',
    //   img: 'assets/images/legs (12).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs13',
    //   title: 'front squats',
    //   img: 'assets/images/legs (13).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs14',
    //   title: 'sumo deadlifts',
    //   img: 'assets/images/legs (14).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs15',
    //   title: 'power squats',
    //   img: 'assets/images/legs (15).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'legs16',
      title: 'angled leg press',
      img: 'assets/images/legs (16).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'legs17',
    //   title: 'hack squats',
    //   img: 'assets/images/legs (17).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs18',
    //   title: 'dumbbell deadlift',
    //   img: 'assets/images/legs (18).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs19',
    //   title: 'side lunges',
    //   img: 'assets/images/legs (19).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'legs20',
    //   title: 'dumbbell split squat',
    //   img: 'assets/images/legs (20).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'legs21',
      title: 'dumbbell step squat',
      img: 'assets/images/legs (21).jpg',
      desc: 'desc',
    },
    {
      ex: 'legs22',
      title: 'squat',
      img: 'assets/images/legs (22).jpg',
      desc: 'desc',
    },
  ],
  rest: [
    {
      ex: 'rest1',
      title: 'reversr wrist curls',
      img: 'assets/images/rest (1).jpg',
      desc: 'desc',
    },
    {
      ex: 'rest2',
      title: 'wrist curls',
      img: 'assets/images/rest (2).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'rest3',
    //   title: 'barbell behind the back wrist curl',
    //   img: 'assets/images/rest (3).jpg',
    //   desc: 'desc',
    // },
  ],
  traps: [
    // {
    //   ex: 'traps1',
    //   title: 'barbell upright rows',
    //   img: 'assets/images/traps (1).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'traps2',
    //   title: 'barbell shrugs',
    //   img: 'assets/images/traps (2).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'traps3',
      title: 'dumbbell shrugs',
      img: 'assets/images/traps (3).jpg',
      desc: 'desc',
    },
  ],
  triceps: [
    {
      ex: 'triceps1',
      title: 'pushdowns',
      img: 'assets/images/triceps (1).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'triceps2',
    //   title: 'close grip pushup',
    //   img: 'assets/images/triceps (2).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps3',
    //   title: 'reverse pushdowns',
    //   img: 'assets/images/triceps (3).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps4',
    //   title: 'wide grip pull up',
    //   img: 'assets/images/triceps (4).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps5',
    //   title: 'one-arm reverse pushdown',
    //   img: 'assets/images/triceps (5).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps6',
    //   title: 'bench dips',
    //   img: 'assets/images/triceps (6).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps7',
    //   title: 'lying triceps extension',
    //   img: 'assets/images/triceps (7).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'triceps8',
    //   title: 'dumbbell triceps extensions',
    //   img: 'assets/images/triceps (8).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'triceps9',
      title: 'one-arm dumbbell triceps extensions',
      img: 'assets/images/triceps (9).jpg',
      desc: 'desc',
    },
    {
      ex: 'triceps10',
      title: 'seated dumbbell triceps extensions',
      img: 'assets/images/triceps (10).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'triceps11',
    //   title: 'seated ex-bar triceps extensions',
    //   img: 'assets/images/triceps (11).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'triceps12',
      title: 'dumbbell triceps kickback',
      img: 'assets/images/triceps (12).jpg',
      desc: 'desc',
    },
    {
      ex: 'triceps13',
      title: 'rope push down',
      img: 'assets/images/triceps (13).jpg',
      desc: 'desc',
    },
    {
      ex: 'triceps14',
      title: 'rope push down',
      img: 'assets/images/triceps (14).jpg',
      desc: 'desc',
    },
    {
      ex: 'triceps15',
      title: 'seating trieceps',
      img: 'assets/images/triceps (15).jpg',
      desc: 'desc',
    },
  ],
  chest: [
    {
      ex: 'chest1',
      title: 'bench press',
      img: 'assets/images/chest (1).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'chest2',
    //   title: 'close grip bench press',
    //   img: 'assets/images/chest (2).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'chest3',
      title: 'incline press',
      img: 'assets/images/chest (3).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'chest4',
    //   title: 'decline press',
    //   img: 'assets/images/chest (4).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'chest5',
    //   title: 'push ups',
    //   img: 'assets/images/chest (5).jpg',
    //   desc: 'desc',
    // },
    // {
    //   ex: 'chest6',
    //   title: 'parallel bar dips',
    //   img: 'assets/images/chest (6).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'chest7',
      title: 'dumbbell press',
      img: 'assets/images/chest (7).jpg',
      desc: 'desc',
    },
    {
      ex: 'chest8',
      title: 'dumbbell flys',
      img: 'assets/images/chest (8).jpg',
      desc: 'desc',
    },
    {
      ex: 'chest9',
      title: 'incline dumbbell press',
      img: 'assets/images/chest (9).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'chest10',
    //   title: 'incline dumbbell flys',
    //   img: 'assets/images/chest (10).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'chest11',
      title: 'pec deck flys',
      img: 'assets/images/chest (11).jpg',
      desc: 'desc',
    },
    {
      ex: 'chest12',
      title: 'cable crossover flys',
      img: 'assets/images/chest (12).jpg',
      desc: 'desc',
    },
    {
      ex: 'chest13',
      title: 'dumbbell pullovers',
      img: 'assets/images/chest (13).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'chest14',
    //   title: 'barbell pullovers',
    //   img: 'assets/images/chest (14).jpg',
    //   desc: 'desc',
    // },
    {
      ex: 'chest15',
      title: 'decline dumbbell bench press',
      img: 'assets/images/chest (15).jpg',
      desc: 'desc',
    },
    // {
    //   ex: 'chest16',
    //   title: 'one arm pushup',
    //   img: 'assets/images/chest (16).jpg',
    //   desc: 'desc',
    // },
  ]
};
